### ISSUE TITLE
When the tree has more than two levels, there will be an error in inserting rows at the last level

### ISSUE THREAD

**Issue by azy58789250** [handsontable/handsontable#10016]
[Demo](https://jsfiddle.net/d8or0nvf/)

**Comment by AMBudnik** [comment]
Hi @azy58789250 

This issue seems to be the same as https://github.com/handsontable/handsontable/issues/9670 where we get the 

```js
Uncaught TypeError: Cannot read properties of undefined (reading '__children')
    at DataManager.hasChildren (handsontable.full.js:157357:24)
    at HeadersUI.appendLevelIndicators (handsontable.full.js:90681:28)
    at NestedRows.onAfterGetRowHeader (handsontable.full.js:156660:22)
    at Core.<anonymous> (handsontable.full.js:156437:43)
    at fastCall (handsontable.full.js:6740:17)
    at Hooks.run (handsontable.full.js:9147:47)
    at Core.runHooks (handsontable.full.js:72873:48)
    at TableView.appendRowHeader (handsontable.full.js:102311:21)
    at Array.<anonymous> (handsontable.full.js:101771:22)
    at RowHeadersRenderer.render (handsontable.full.js:104342:49)

```

error once we pick `Add row above` or `Add row below`. And the data is mostly erased
<img width="355" alt="Screenshot 2022-10-13 at 09 26 24" src="https://user-images.githubusercontent.com/10757813/195530117-c8e2a884-bf6a-45a8-93b9-b14b49d9e321.png">

Could you please check if it works the same in your project?

**Comment by AMBudnik** [comment]
Hi @azy58789250 

do we have any updates regarding this case? I will keep it closed (as I think that it's the same as https://github.com/handsontable/handsontable/issues/9670). But If I'm wrong, please provide the details, and we'll reopen this report.
