### ISSUE TITLE
Can I use vue3 component in Custom renderer? I just find declare a renderer as a function in the doc.

### ISSUE THREAD

**Issue by whispergong** [handsontable/handsontable#10257]
I know we can use vue2 component as a custom renderer.
https://handsontable.com/docs/javascript-data-grid/vue-hot-column/#declare-a-custom-renderer-as-a-component

But what about vue3.I can't find example.
https://handsontable.com/docs/javascript-data-grid/vue3-custom-renderer-example/

Thank you.

**Comment by adrianszymanski89** [comment]
Hi @u373693041 

Thank you for pointing that out. Indeed, a tutorial for component-based custom renderer needs to be included in our Vue 3 guide. The example from Vue 2 cannot be easily modified and needs to be rewritten for the new version. For the time being, I recommend using a function-based renderer.

**Comment by u373693041** [comment]
> Hi @u373693041
> 
> Thank you for pointing that out. Indeed, a tutorial for component-based custom renderer needs to be included in our Vue 3 guide. The example from Vue 2 cannot be easily modified and needs to be rewritten for the new version. For the time being, I recommend using a function-based renderer.

Does this mean that we can use vue3 component as renderer now.
Can you tell me how to use it here, because I can only use vue3 component as renderer at present. 
thank you.

**Comment by adrianszymanski89** [comment]
Currently, it's not possible with the example that we had in Vue 2 guide. We need to rewrite it for Vue 3.

**Comment by u373693041** [comment]
I refer to the writing method of hand-contable/vue2 and write the renderer function so that it can use the vue3 component as the renderer for the reference of those who need to use it.
```
<script setup>
import { HotTable } from '@handsontable/vue3'
import { registerAllModules } from 'handsontable/registry'
import 'handsontable/dist/handsontable.full.css'
import { ref, render, h, getCurrentInstance } from 'vue'
import CustomRenderer from './CustomRenderer.vue'

const licenseKey = 'non-commercial-and-evaluation'

registerAllModules()

const app = getCurrentInstance()

const tableData = ref([
    ['A1', 'B1'],
    ['A2', 'B2'],
    ['A3', 'B3'],
    ['A4', 'B4'],
    ['A5', 'B5'],
    ['A6', 'B6'],
    ['A7', 'B7'],
    ['A8', 'B8'],
    ['A9', 'B9'],
    ['A10', 'B10'],
])

const rendererCache = {}

const renderTdFn = (instance, td, row, col, prop, value) => {
    if (td?.getAttribute('ghost-table')) {
        return td
    }

    let cachedEntry = rendererCache[`${row}-${col}`]
    let vueComponent = rendererCache[`${row}-${col}`]?.component

    if (vueComponent) {
        Object.assign(vueComponent.component.props, {
            instance, td, row, col, prop, value,
        })
    } else {
        vueComponent = h(CustomRenderer, {
            instance, td, row, col, prop, value,
        })

        vueComponent.appContext = app.appContext

        rendererCache[`${row}-${col}`] = {
            component: vueComponent,
            id: `${row}-${col}`,
            lastUsedTD: null,
        }

        cachedEntry = rendererCache[`${row}-${col}`]
    }

    if (!vueComponent.el?.parentElement || cachedEntry?.lastUsedTD !== td) {
        while (td.firstChild) {
            td.removeChild(td.firstChild)
        }

        render(vueComponent, td)

        cachedEntry.lastUsedTD = td
    }

    return td
}

const columnsConfig = [
    {
        renderer: renderTdFn,
    },
]
</script>

<template>
    <HotTable
        :data="tableData"
        :row-headers="true"
        :col-headers="true"
        :context-menu="true"
        :merge-cells="true"
        :license-key="licenseKey"
        :columns="columnsConfig"
    />
</template>
```

**Comment by u373693041** [comment]
But I found that when I insert a row using ContextMenu in this renderer
```
view.mjs:205 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'tagName')
    at SharedOrderView2.render (view.mjs:205:16)
    at CellsRenderer2.render (cells.mjs:110:21)
    at TableRenderer2.render (table.mjs:299:18)
    at Renderer2.render (index.mjs:115:21)
    at MasterTable2.draw (table.mjs:334:153)
    at Walkontable2.draw (_base.mjs:143:22)
    at WalkontableFacade2.draw (core.mjs:181:17)
    at TableView2.render (tableView.mjs:202:18)
    at Core._refreshBorders (core.mjs:4370:19)
    at Selection3.<anonymous> (core.mjs:395:11)
```
![image](https://user-images.githubusercontent.com/48196776/221509605-94cc16b2-fb6e-4558-80fb-3d341167b823.png)

**Comment by super-programmer** [comment]
> Currently, it's not possible with the example that we had in Vue 2 guide. We need to rewrite it for Vue 3.

When will the rewrite be finished

**Comment by adrianszymanski89** [comment]
Hi @super-programmer 

This issue isn't on our roadmap yet.

**Comment by parkjunghwan-reco** [comment]
@adrianszymanski89 
hello..
Is component rendering impossible in vue3?

**Comment by adrianszymanski89** [comment]
Hi @parkjunghwan-reco 

Unfortunately, no. It still needs to be investigated further. We will update this topic once it gets on our roadmap.

**Comment by saragrigolin** [comment]
Hello @adrianszymanski89,

Are there any updates on this topic? I'm really looking forward to using Handsontable with Vue 3, but the inability to use a custom component in a custom renderer is a major blocker for me.

**Comment by adrianszymanski89** [comment]
Hi @saragrigolin 

Not yet. Currently, we are focusing on other projects.

**Comment by adrianszymanski89** [comment]
Hi @sakura-flutter 

Thank you for providing the workaround for others. We appreciate your input.

**Comment by adrianspdev** [comment]
Hi @whispergong (and others following this thread),

Vue 3 component-based custom renderers are now documented. The guide page Vue 3 custom renderer example has a new section, "Declare a renderer as a Vue 3 component", with a runnable example that mounts a Vue 3 SFC into the cell's TD from inside the renderer function
using Vue's public h() + render(vnode, container) API. The same section also points to createApp(Component, props).mount(td) for cases where you need an app context (provide/inject, global components, plugins).

No wrapper change was required - the pattern uses public Vue 3 and Handsontable APIs against the current @handsontable/vue3 release.

Shipped in PR #12525. Closing this issue - feel free to reopen if anything is missing or unclear.

Thanks everyone for the workarounds posted along the way.
