### ISSUE TITLE
[Bug]: getSourceData fails with "TypeError: name.split is not a function" when function data source produces DocumentFragments

### ISSUE THREAD

**Issue by rfricz** [handsontable/handsontable#10397]
### Describe the bug

Having a function data source that returns DocumentFragments or div elements, when the `getSourceData` method is called with the optional range arguments, it doesn’t return a subarray from the source data but fails with `TypeError: name.split is not a function`:
```
Uncaught TypeError: name.split is not a function
    at setProperty (handsontable.full.js:751:20)
    at handsontable.full.js:102566:41
    at rangeEach (handsontable.full.js:4219:9)
    at DataSource.getAtRow (handsontable.full.js:102559:33)
    at handsontable.full.js:102687:97
    at rangeEach (handsontable.full.js:4219:9)
    at DataSource.getByRange (handsontable.full.js:102686:29)
    at Core.getSourceData (handsontable.full.js:65502:25)
```
Pressing the button at the top in the JSFiddle triggers this.

The method works fine when the range arguments are omitted, but no method is needed for that case.

### Provide a link to the demo with the bug reproduction

https://jsfiddle.net/z2r4pe89/

### Handsontable version

12.4.0

### Your environment

Chromium 112 & Firefox 113, Windows 10

**Comment by adrianszymanski89** [comment]
Hi @rfricz 

Thank you for reporting this. I'm convinced that the source of this issue is the same one as in your previous one reported here: https://github.com/handsontable/handsontable/issues/10385.

I know that my colleague already updated you on the status of the research there so we will be in touch.

**Comment by adrianspdev** [comment]
Hi @rfricz,

Verified on current develop (17.0.1) — original `TypeError: name.split is not a function` no longer reproduces. Fix landed in PR #11565.

Closing this issue. If you still hit related behavior on a recent version, feel free to reopen with a fresh repro.
