### ISSUE TITLE
[Bug]: validateCell fails because cellProperties doesn't contains prop field

### ISSUE THREAD

**Issue by emadebManyDesigns** [handsontable/handsontable#10549]
### Describe the bug

In the _core.js_ file, the _validateCell_ function send to the hooks the _cellProperties.prop_ field, but sometimes this field is undefined, so the validation fails with the error 
```
Error: Assertion failed: Expecting an unsigned number.
    at assert (handsontable.full.js:99448:11)
    at LazyFactoryMap.obtain (handsontable.full.js:104541:23)
    at CellMeta.getMeta (handsontable.full.js:104821:53)
    at MetaManager.getCellMeta (handsontable.full.js:99093:36)
    at Core.getCellMeta (handsontable.full.js:46116:24)
    at Core.<anonymous> (handsontable.full.js:110092:25)
    at fastCall (handsontable.full.js:74774:17)
    at Hooks.run (handsontable.full.js:78880:46)
    at Core.runHooks (handsontable.full.js:47284:48)
    at Core.validateCell (handsontable.full.js:44377:24)
```

A possible fix is to init the _prop_ field when it is undefined
```
  this.validateCell = function(value, cellProperties, callback, source) {
    if (cellProperties && cellProperties.prop === undefined) {
      cellProperties.prop = instance.colToProp(cellProperties.visualCol);
    }

    let validator = ...
```

### Video/Screenshots

![immagine](https://github.com/handsontable/handsontable/assets/41444394/d3643d37-c521-42a6-8a6c-a48465de976c)

### Handsontable version

13.1.0

### Your environment

Firefox, Windows 10

**Comment by adrianszymanski89** [comment]
Hi @emadebManyDesigns 

Thank you for catching and reporting this. I'll report this internally to our developers, but if you have a possible solution, you can also create a PR.

**Comment by emadebManyDesigns** [comment]
I'm sorry, i never make a PR 😥
How can I create it?
I suppose I need to create a brunch of develop or something of similar, but I can't see any "new branch" button.

**Comment by adrianszymanski89** [comment]
Hi @emadebManyDesigns 

No worries if you don't have experience with PRs we'll fix it on our side. I mentioned it because sometimes our users decide to prepare PRs for us if they already have a possible solution.

**Comment by ottosson** [comment]
I've just experienced this issue as well. Same error message and call stack. But it happens when I run 
```hot.populateFromArray(0, 0, newTableData);```

```
utils.mjs:101  Uncaught (in promise) Error: Assertion failed: Expecting an unsigned number.
    at assert (utils.mjs:101:11)
    at LazyFactoryMap.obtain (lazyFactoryMap.mjs:173:5)
    at CellMeta.getMeta (cellMeta.mjs:125:53)
    at MetaManager.getCellMeta (index.mjs:146:36)
    at Core.getCellMeta (core.mjs:3113:24)
    at Core.<anonymous> (dropdownEditor.mjs:29:25)
    at fastCall (function.mjs:289:17)
    at Hooks.run (pluginHooks.mjs:2797:23)
    at Core.runHooks (core.mjs:4426:33)
    at Core.validateCell (core.mjs:1366:24)
```

No idea why it happens. Seems to me to be valid input (newTableData).

**Comment by adrianszymanski89** [comment]
Hi @ottosson 

Thank you for additional details. Are you also experiencing this issue during the validation process or just using `populateFromArray`?

**Comment by ottosson** [comment]
I think it's when the cells are validated. It happens when I have columns of type "dropdown" but not when they are edit: "select"

**Comment by adrianszymanski89** [comment]
Yes, setting the type automatically attaches the validator to the cell. So, in this case, it will also validate the source.

**Comment by ottosson** [comment]
Another clue: Seems to happen when I moved the populateFromArray into a hot.batch, but works when I do it outside batch

**Comment by adrianszymanski89** [comment]
Hi @ottosson 

Once again, thank you for all the details. We appreciate it, and I'm sure those will be helpful for our developers during the fixing process.

**Comment by adrianspdev** [comment]
Hi @emadebManyDesigns,

Tested against Handsontable v17.0.1 and current develop using your exact snippet:

- columns config with string data keys
- afterUpdateSettings checks Object.keys(newSettings).includes('data') → calls validateCells()
- updateSettings({ data: [...] }) triggers the path

Both builds run validateCells() cleanly. No Assertion failed: Expecting an unsigned number from LazyFactoryMap.obtain. No uncaught exceptions.

In v17, cellProperties.prop is initialized in `src/dataMap/metaManager/mods/dynamicCellMeta.js` (extendCellMeta sets cellMeta.prop = hot.colToProp(visualCol) before any hook reads it). The v13.1.0 path lacked this guarantee. Fix appears to have landed indirectly through `metaManager` refactoring between v13 and v17.

Closing as resolved. Feel free to reopen if you can still reproduce on v17.0.1 with a minimal repro.
