### ISSUE TITLE
[Bug]: Error when adding column

### ISSUE THREAD

**Issue by mtjoe3** [handsontable/handsontable#10569]
### Description

Error doing this series of actions:
1. Create row below last row
1. Create another row below last row
1. Add in formula to a cell in the last row
1. Create column before/after any column
1. Table will free and this console error appear

```
handsontable.full.js:51693 Uncaught TypeError: Cannot read properties of undefined (reading 'splice')
    at DenseStrategy.addColumns (handsontable.full.js:51693:45)
    at AddressMapping.addColumns (handsontable.full.js:48303:20)
    at handsontable.full.js:60840:31
    at EmptyStatistics.measure (handsontable.full.js:47949:20)
    at DependencyGraph.addColumns (handsontable.full.js:60839:18)
    at Operations.doAddColumns (handsontable.full.js:42318:57)
    at Operations.addColumns (handsontable.full.js:41491:16)
    at CrudOperations.addColumns (handsontable.full.js:110307:23)
    at HyperFormula.addColumns (handsontable.full.js:32179:66)
    at Formulas.onAfterCreateCol (handsontable.full.js:58836:33)
```

### Video or screenshots

https://github.com/handsontable/hyperformula/assets/83485085/4abf2da7-0921-4b8c-9942-fc6d7ad7a486

### Demo

https://jsfiddle.net/to3wk2ej/1/

### HyperFormula version

12

### Your framework

Native JS

### Your environment

Chrome 119

**Comment by AMBudnik** [comment]
Hi @mtjoe3 

Thank you for sharing the issue.

As it is within the plugin I changed the repository to /handsontable.

I was able to replicate the issue using your scenarios in a simplied version of the example https://jsfiddle.net/x38wuvoq/ (using v13.1.0 - latest version).

**Comment by thanhlevu** [comment]
I have the same problem using handsontable^14.0.0

**Comment by AMBudnik** [comment]
Hi @thanhlevu yes, this issue is not solved yet. However, I will make sure to notify you as soon as we fix it.

**Comment by lizzie-gasson-m** [comment]
Hi @AMBudnik, just interested to know if there is any planned timeline for this issue to be fixed? Thanks

**Comment by AMBudnik** [comment]
@lizzie-gasson-m, we will publish 14.1 around the 16th of January, and 14.2 is already planned, so the first possible date is post-14.2 (in March).

**Comment by AMBudnik** [comment]
Hi @mtjoe3 @lizzie-gasson-m I am more than happy to announce that this issue is no longer replicable.

Once you update dependencies in Hadndsontable it will fetch Hyperformula 2.7.1 that fixed the issue.

I am closing this issue as done.

If you'd find any difficulties, please let me know here on GitHub or contact us at support@handsontable.com
