### ISSUE TITLE
A `Sheet size limit exceeded` error is being thrown when using multiple Hot instances in separate React components with a single Hyperformula instance.

### ISSUE THREAD

**Issue by wave-light** [handsontable/handsontable#10672]
### Describe the bug

When using the formulas plugin with multiple sheets defined in separate React components, if one of the sheets has `maxRows` prop set to a number which is less than the number of data-containing rows in another sheet, an error is thrown when the Hot component is updated.

For example:
- In this example scenario, we have a single Hyperformula instance called `hfInstance`.
- Component1 contains a Hot instance (HotInstance1), which has `maxRows` prop set to 2, and is connected to the `hfInstance` using the `formulas` prop.
- Component2 contains a different Hot instance (HotInstance2), which has the first 5 rows populated with data, and is also connected to the `hfInstance` using the `formulas` prop.
- If Component1 updates for some reason, for example a state update, HotInstance1 will throw an error.

The reason for the error, is that the `maxRows` of 2 on the Sheet1 is being compared against number of rows in the bounds of Sheet2.
This comparison is occurring in Hyperformula's BuildEngineFactory, on line 63.

Here is the stack trace:
<pre>
react-dom.development.js:22839 Uncaught Error: Sheet size limit exceeded
    at BuildEngineFactory.buildEngine (BuildEngineFactory.js:63:17)
    at BuildEngineFactory.rebuildWithConfig (BuildEngineFactory.js:46:17)
    at _HyperFormula.rebuildWithConfig (HyperFormula.js:4123:42)
    at _HyperFormula.updateConfig (HyperFormula.js:864:10)
    at Formulas.updatePlugin (formulas.mjs:652:19)
    at Formulas.onUpdateSettings (base.mjs:250:14)
    at Core.<anonymous> (base.mjs:108:65)
    at fastCall (function.mjs:295:17)
    at Hooks.run (pluginHooks.mjs:2821:23)
    at Core.runHooks (core.mjs:4426:33)
</pre>

### Video/Screenshots

https://github.com/handsontable/handsontable/assets/40989533/28382887-3e7c-420a-a501-00d43f3b31ca

### Provide a link to the demo with the bug reproduction

https://stackblitz.com/edit/stackblitz-starters-cgyc6p?description=React%20%20%20TypeScript%20starter%20project&file=package.json,src%2FApp.tsx&title=React%20Starter

### Handsontable version

14.0.0

### Your environment

MacOS, Google Chrome

**Comment by adrianszymanski89** [comment]
Hi @wave-light 

Thank you for reporting this. I checked the issue, and it's related to the HyperFormula itself, and the limit set for `maxRows` in the engine is too small. 

We have a similar issue reported here: https://github.com/handsontable/hyperformula/issues/1185.

In this case, the same problem was found in the `maxColumns`, but I believe the reason is the same. I will report it internally and let you know when we have more information on the possible timeline for the fix.

**Comment by sequba** [comment]
### The cause of the error

The `Formulas.updatePlugin` method passes the `maxRows` and `maxColumns` settings to the HyperFormula engine. But in HyperFormula the [maxRows](https://hyperformula.handsontable.com/api/interfaces/configparams.html#maxrows) and [maxColumns](https://hyperformula.handsontable.com/api/interfaces/configparams.html#maxcolumns) config options are global and hold for all sheets.

Relevant `formulas` plugin code:

https://github.com/handsontable/handsontable/blob/1570df1889464e95ec580c06d965912508c6a96f/handsontable/src/plugins/formulas/formulas.js#L323-L328

https://github.com/handsontable/handsontable/blob/1570df1889464e95ec580c06d965912508c6a96f/handsontable/src/plugins/formulas/engine/settings.js#L39-L45

### Recommended solution

`maxRows` and `maxColumns` settings in Handsontable seem to control the visual layer (the number of rows and columns displayed), whereas in HyperFormula, the `maxRows` and `maxColumns` config options were introduced for performance reasons. In my opinion, Handsontable should not pass these settings to HyperFormula.

To fix the issue, it should be enough to remove lines 41 and 42 from the `handsontable/src/plugins/formulas/engine/settings.js` file:

https://github.com/handsontable/handsontable/blob/1570df1889464e95ec580c06d965912508c6a96f/handsontable/src/plugins/formulas/engine/settings.js#L41-L42

**Comment by budnix** [comment]
Thanks for reporting the bug — the fix is already done (https://github.com/handsontable/handsontable/pull/13218) and will be released in upcoming releases.
