### ISSUE TITLE
registerAllModules() not working in an Electron environment with nodeIntegration:false, contextIsolation:true - Unable to connect with Hyperformula

### ISSUE THREAD

**Issue by Kashi-Datum** [handsontable/handsontable#11157]
### Describe the bug

I am unable to get ```registerAllModules``` to run properly with ```nodeIntegration:false, contextIsolation:true``` inside of an Electron app.

In an Electron environment running:
React + Typescript, (https://www.electronforge.io/guides/framework-integration/react-with-typescript),

I have tried passing ```registerAllModules``` through a preload script, however this still does not allow Hyperformula to work properly with the spreadsheet.

A simple minimum viable example of the error can be seen below in a simple react webpage

```
// index.tsx
import * as React from 'react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { createModelTableGrid } from '../components/createModelTableGrid';
import 'handsontable/dist/handsontable.full.min.css';

// Handsontable
import Handsontable from 'handsontable/base';
import { HotTable } from '@handsontable/react';
import { HyperFormula } from 'hyperformula';
import { registerAllModules } from 'handsontable/registry';
registerAllModules();

function HomepagePage() {
	return (
		<div className="p-4">
			<ModelTableGrid></ModelTableGrid>
			<Link to="/test">
				<div className="btn">Navigate</div>
			</Link>
		</div>
	);
}

function ModelTableGrid() {
	// const data = createModelTableGrid();
	const [data, setData] = useState(createModelTableGrid());
	console.log('data:');
	console.log(data);
	return (
		<HotTable
			formulas={{ engine: { hyperformula: HyperFormula } }}
			rowHeaders={true}
			colHeaders={true}
			height="auto"
			width="auto"
			// type="numeric"
			autoWrapRow={true}
			autoWrapCol={true}
			allowEmpty={true}
			// cells={(row, col, prop) => {
			// 	return {
			// 		type: 'numeric',
			// 		numericFormat: { pattern: { mantissa: 0, negative: 'parenthesis', thousandSeparated: true }, culture: 'en-US' }
			// 	};
			// }}
			// columns={[{}, { type: 'numeric', numericFormat: { pattern: '$0,0.00', culture: 'en-US' } }]}
			// minSpareCols={1}
			// minSpareRows={1}
			licenseKey="non-commercial-and-evaluation" // for non-commercial use only
			data={data}
		/>
	);
}

export { HomepagePage as default };

```

Results in the following error:

```
Uncaught ReferenceError: require is not defined
    at a (numbro.min.js:1:403)
    at eval (numbro.min.js:1:453)
    at eval (numbro.min.js:1:37)
    at eval (numbro.min.js:1:49)
    at ./node_modules/handsontable/node_modules/numbro/dist/numbro.min.js (index.js:2436:1)
    at __webpack_require__ (index.js:10178:32)
    at fn (index.js:10415:21)
    at eval (numericRenderer.js:7:38)
    at ./node_modules/handsontable/renderers/numericRenderer/numericRenderer.js (index.js:5164:1)
    at __webpack_require__ (index.js:10178:32)
```

Setting ```nodeIntegration: true, contextIsolation: false``` fixes the issue however this is not secure and in general should not be something that you do in a production Electron application.

If, instead, we try to pass the function call through the preload, no error pops up however it is clear that the Hyperformula engine is not working as intended.

```preload.ts```
```
import { contextBridge, ipcRenderer } from 'electron';
import Handsontable from 'handsontable/base';
import { HotTable } from '@handsontable/react';
import { HyperFormula } from 'hyperformula';
import { registerAllModules } from 'handsontable/registry';

contextBridge.exposeInMainWorld('registerAllModules', registerAllModules);
```

### Handsontable version

14.3.0

### Your environment

Electron, Windows 11

**Comment by adrianszymanski89** [comment]
Hi @Kashi-Datum 

Thank you for contacting us. I tried to reproduce the scenario locally, but some imports are missing in the code snippet you sent. Can you please send a code demo in StackBlitz so we can check it?

**Comment by AMBudnik** [comment]
Hi @Kashi-Datum 

Do you still experience issues while registering plugins?
