### ISSUE TITLE
Error when running demo code in React/Typescript environment

### ISSUE THREAD

**Issue by ankitgoyal100** [handsontable/handsontable#7569]
### Description
Running into the following issue when I try the demo code:
```
semantic error TS2607: JSX element class does not support attributes because it does not have a 'props' property.
Error: /Users/ankitgoyal/Documents/dropdoc/src/DataUploadModal.tsx(109,7): semantic error TS2607: JSX element class does not support attributes because it does not have a 'props' property.
    at error (/Users/ankitgoyal/Documents/dropdoc/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at throwPluginError (/Users/ankitgoyal/Documents/dropdoc/node_modules/rollup/dist/shared/node-entry.js:11878:12)
    at Object.error (/Users/ankitgoyal/Documents/dropdoc/node_modules/rollup/dist/shared/node-entry.js:12912:24)
    at Object.error (/Users/ankitgoyal/Documents/dropdoc/node_modules/rollup/dist/shared/node-entry.js:12081:38)
    at RollupContext.error (/Users/ankitgoyal/Documents/dropdoc/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:17194:30)
    at /Users/ankitgoyal/Documents/dropdoc/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24958:23
    at arrayEach (/Users/ankitgoyal/Documents/dropdoc/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:534:11)
    at forEach (/Users/ankitgoyal/Documents/dropdoc/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:9360:14)
    at printDiagnostics (/Users/ankitgoyal/Documents/dropdoc/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24931:5)
    at Object.transform (/Users/ankitgoyal/Documents/dropdoc/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:27374:17)
```

### Code
```
const data = Handsontable.helper.createSpreadsheetData(6, 10);

return (
  <div>
    <HotTable
      id="hot"
      data={data}
      colHeaders={true}
      rowHeaders={true}
      />
  </div>
);
```

### Environment
```
"@handsontable/react": "^4.0.0",
"handsontable": "^8.2.0",
```

**Comment by AMBudnik** [comment]
This topic hasn't been updated for a while.
@ankitgoyal100 please send me a message to support@handsontable.com if you are still having issues with the following case (or any other as well).
