### ISSUE TITLE
Missing support for Node >=16.14.0

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9149]
### Description

The monorepo is not usable on Node 17. There are several errors in the common commands such as:
 1) `npm run build` throws `TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///Users/budnix/Documents/Projects/handsontable-develop/package.json" needs an import assertion of type "json"`; So that, all NPM scripts executed in the root directory does not work; 
 2)  `npm run build` (within `./handsontable`) throws Webpack error `Error: error:0308010C:digital envelope routines::unsupported`.
 3) `verify-build.mjs` used in freezing CI command (@jansiegel knows the details)

The errors occur in all Node 17 versions.

<details>
<summary>Logs ad 1</summary>

```log
> cross-env-shell COMMAND_ENV=all node --experimental-json-modules scripts/translate-to-native-npm.mjs "build"

node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///Users/budnix/Documents/Projects/handsontable-develop/package.json" needs an import assertion of type "json"
    at new NodeError (node:internal/errors:371:5)
    at validateAssertions (node:internal/modules/esm/assert:82:15)
    at defaultLoad (node:internal/modules/esm/load:24:3)
    at ESMLoader.load (node:internal/modules/esm/loader:359:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:58)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:297:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:261:34)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:81:21)
    at async Promise.all (index 1) {
  code: 'ERR_IMPORT_ASSERTION_TYPE_MISSING'
}

Node.js v17.4.0
```
</details>
<details>
<summary>Logs ad 2</summary>

```log
> handsontable@11.1.0 build:umd
> cross-env-shell BABEL_ENV=commonjs NODE_ENV=development env-cmd -f ../hot.config.js webpack --hide-modules

  build [==                  ] 10% (0.0 seconds)node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/Users/budnix/Documents/Projects/handsontable-develop/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/budnix/Documents/Projects/handsontable-develop/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/budnix/Documents/Projects/handsontable-develop/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/budnix/Documents/Projects/handsontable-develop/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/budnix/Documents/Projects/handsontable-develop/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/budnix/Documents/Projects/handsontable-develop/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/budnix/Documents/Projects/handsontable-develop/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/budnix/Documents/Projects/handsontable-develop/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/budnix/Documents/Projects/handsontable-develop/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/Users/budnix/Documents/Projects/handsontable-develop/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/budnix/Documents/Projects/handsontable-develop/node_modules/babel-loader/lib/index.js:59:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.4.0
```

</details>

Edit _(11 of February 2022)_: After updating Node to 16.14 (from 16.13) the monorepo commands (e.g. `npm run in handsontable lint`) do not work as well.

### Steps to reproduce

1. Install the Node v17;
2. Run `npm run build` command

### Your environment
* Handsontable version: -
* Browser name and version: -
* Operating system: macOs

**Comment by warpech** [comment]
Today we decided to limit the scope of this issue to the problems occurring in Node 16.x LTS. Problems related only to Node 17 should be pushed out to a separate issue. 

Target for this issue is to enable using the newest 16.x in the build process.
