### ISSUE TITLE
[8.0.0+] Multiple actions of enabling and disabling the `columnSorting` plugin breaks table with an error in the console

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#9207]
### Description

Multiple actions of enabling and disabling the `columnSorting` plugin break it with an error in the console. After we receive this error table becomes immune to any event and throws additional errors. 

### Steps to reproduce

1. Sort any column
2. Click the button above the table 3 times to get the error

```js
handsontable.full.js:21133 Uncaught TypeError: Cannot read properties of null (reading 'slice')
    at IndexesSequence.setValues (handsontable.full.js:21133:35)
    at IndexMapper.setIndexesSequence (handsontable.full.js:68143:28)
    at handsontable.full.js:84030:37
    at Core.batchExecution (handsontable.full.js:32975:18)
    at ColumnSorting.disablePlugin (handsontable.full.js:84028:16)
    at toggleColumnSort (?editor_console=true:140:9)
    at HTMLButtonElement.<anonymous> (?editor_console=true:134:2)
```

### Demo

https://jsfiddle.net/29os1bxz/18/ - 11.1 remains broken
https://jsfiddle.net/29os1bxz/15/ - 7.4.2. last working well
https://jsfiddle.net/29os1bxz/16/ - 8.0.0 first broken

### Your environment
* Handsontable version: 8+
* Browser name and version: Chrome 97
* Operating system: macOS Monterey

Inform [forum](https://forum.handsontable.com/t/toggling-columnsort-plugin/5907)

**Comment by AMBudnik** [comment]
This issue is no longer replicable. Please check the following demo (with Handsontable v14.5.0 loaded) https://jsfiddle.net/0bdtqc5e/ to test the use case. Issue closed as solved.
