### ISSUE TITLE
Calling `updateSettings` within the hook produces error and does not show menu at all

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#9648]
### Description

Calling `updateSettings` within the hook produces error and does not show menu at all

### Steps to reproduce

1. Open any column in the example
2. You will get no response at first, so try again
3. If you try again, you get the following error. In both cases, the menu does not open.

```js
handsontable.full.js:7016 Uncaught TypeError: Cannot read properties of null (reading 'eventListeners')
    at EventManager.addEventListener (handsontable.full.js:7016:20)
    at Menu.menuItemRenderer (handsontable.full.js:56935:27)
    at renderer (handsontable.full.js:56270:27)
    at handsontable.full.js:55659:11
    at arrayEach (handsontable.full.js:1382:9)
    at handsontable.full.js:55644:30
    at Map.forEach (<anonymous>)
    at GhostTable.createCol (handsontable.full.js:55643:20)
    at GhostTable.addColumn (handsontable.full.js:55421:41)
    at handsontable.full.js:141278:38
```

### Demo

http://jsfiddle.net/vugcaL36/ v12

### Your environment
* Handsontable version: 12.1.2
_This issue does not seem to be a regression_
* Browser name and version: Chrome 103
* Operating system: macOS Monterey

Inform [forum](https://forum.handsontable.com/t/update-dropdownmenu-with-updatesettings/6255)

**Comment by rhysmansfield** [comment]
Anything on this guys?

**Comment by adrianszymanski89** [comment]
Hi @rhysmansfield 

Not yet. Any updates will be visible in this issue.

**Comment by adrianspdev** [comment]
Fix merged in #12593. Will ship in one of next releases. Closing now. Thanks!
