### ISSUE TITLE
beforeRemoveRow throws an error while combined with useState

### ISSUE THREAD

**Issue by adrianszymanski89** [handsontable/handsontable#9719]
### Description

Trying to get the removed row index and store it as a state in React produces the following error:

> Uncaught TypeError: Cannot read properties of null (reading 'runHooks')
>     at e.value (handsontable.full.min.js:500:128380)
>     at e.value (handsontable.full.min.js:500:125935)
>     at handsontable.full.min.js:500:21932
>     at o (handsontable.full.min.js:31:10415)
>     at N (handsontable.full.min.js:500:21780)
>     at Object.alter (handsontable.full.min.js:500:22160)
>     at t.default.alter (handsontable.full.min.js:500:36808)
>     at t.default.callback (handsontable.full.min.js:626:157171)
>     at handsontable.full.min.js:500:195452
>     at o (handsontable.full.min.js:31:10415)

### Steps to reproduce
1. Use context menu to remove any row
2. Open dev console to see the error

### Demo

https://jsfiddle.net/mjt2cfky/

### Your environment
* Handsontable version: 12.1
* Browser name and version: Google Chrome 103
* Operating system: macOS Monterey 12.4

**Comment by AMBudnik** [comment]
It works the same for the `afterRemoveRow()` hook. Tested with React 17 and 18.

**Comment by adrianspdev** [comment]
Retested on v17.0.1 and current develop with React 18 + useState + beforeRemoveRow/afterRemoveRow calling setState on row removal:

- No Cannot read properties of null (reading 'runHooks') error.
- Both hooks fire correctly.
- setState updates state (e.g., {"index":1,"amount":1,"physicalRows":[1]}).
- Zero console errors across multiple removals.

Bug fixed between v15.0.0 and v17.0.1. Closing.
