### ISSUE TITLE
We are not able to use `setSourceDataAtCell()` in `afterLoadData()` hook

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#9904]
### Description

We are not able to use `setSourceDataAtCell()` in `afterLoadData()` hook.
I think that this is a limitation as `afterLoadData()` runs before the `modifyData()`. But only by reading the old migration guide we are able to tell that setting source data should be called after `modifyData()` finished its job. 

@kirszenbaum I'm somewhere between adding the info in the docs and popping an error that tells the developer that this method cannot be used in this hook. What do you think?

### The `afterLoadData()` hook

1. Go to https://jsfiddle.net/ef2j5by4/1/
2. Check that the value is not changed (first cell should be zero)
3. Check the console 

**result**
console error
```js
handsontable.full.js:87306 Uncaught TypeError: Cannot read properties of undefined (reading 'getActiveEditor')
    at Core.getActiveEditor (handsontable.full.js:87306:26)
    at Core.setSourceDataAtCell (handsontable.full.js:86010:33)
    at Core.afterLoadData (?editor_console=true:126:9)
    at fastCall (handsontable.full.js:8006:17)
    at Hooks.run (handsontable.full.js:10412:47)
    at Core.runHooks (handsontable.full.js:87459:48)
    at replaceData (handsontable.full.js:133280:15)
    at Core.loadData (handsontable.full.js:85236:30)
    at Core.updateSettings (handsontable.full.js:85458:7)
    at Core.init (handsontable.full.js:84115:10)
```

Table disappears and when we click the empty space where it should be we get another error

```js
handsontable.full.js:2219 Uncaught TypeError: Cannot read properties of undefined (reading 'ownerDocument')
    at offset (handsontable.full.js:2219:30)
    at Autofill.getIfMouseWasDraggedOutside (handsontable.full.js:142757:45)
    at Autofill.onMouseMove (handsontable.full.js:142851:41)
    at HTMLHtmlElement.<anonymous> (handsontable.full.js:142777:23)
    at HTMLHtmlElement.callbackProxy (handsontable.full.js:7009:18)
```

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: 12.1.2
* Browser name and version: Chrome 105
* Operating system: macOS Monterey

**Comment by adrianspdev** [comment]
Fixed in #12585. setSourceDataAtCell() can now be called inside afterLoadData() without throwing. Closing as resolved.
